spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5588
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

    debug: true
    spring:
      devtools:
        restart:
          enabled: true  #设置开启热部署
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效